export const SET_PHOTOS_LIST = 'SET_PHOTOS_LIST';
export const CLEAR_PHOTOS_LIST = 'CLEAR_PHOTOS_LIST';
export const SET_CURRENT_PHOTO = 'SET_CURRENT_PHOTO';
export const SET_URL_PHOTO = 'SET_URL_PHOTO';
